services:
  mysql:
    image: "mysql:8.4.4"
    environment:
      - "MYSQL_DATABASE=showdown_competition"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=bingo_admin"
    ports:
      - "3306"
  redis:
    image: "redis:7.4.2-alpine"
    ports:
      - "6379"
