services:
  java:
    image: "bingo:0.0.1-SNAPSHOT"
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:8080"
  mysql:
    image: "mysql:8.4.4"
    environment:
      - "MYSQL_DATABASE=showdown_competition"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=bingo_admin"
    ports:
      - "3001:3306"
  redis:
    image: "redis:7.4.2-alpine"
    ports:
      - "3002:6379"
networks:
  showdown-network:
    driver: bridge
